# Generated by Django 3.2 on 2023-12-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('customer_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('given_name', models.CharField(default='John', max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=2)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger')),
            ],
        ),
    ]
