# Generated by Django 3.2 on 2023-12-03 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
