# Generated by Django 3.2 on 2023-12-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('crew_in_charge', models.CharField(default='John Doe', max_length=200)),
                ('task', models.CharField(default='Routine inspection', max_length=200)),
                ('condition', models.CharField(choices=[('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Good', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('series_type', models.CharField(default='A', max_length=1)),
                ('model_number', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=0)),
                ('num_seats', models.IntegerField(default=0)),
                ('num_toilets', models.IntegerField(default=0)),
                ('has_reclining_seats', models.BooleanField(default=False)),
                ('has_folding_tables', models.BooleanField(default=False)),
                ('has_disability_access', models.BooleanField(default=False)),
                ('has_luggage_storage', models.BooleanField(default=False)),
                ('has_vending_machines', models.BooleanField(default=False)),
                ('has_food_service', models.BooleanField(default=False)),
            ],
        ),
    ]
