# Generated by Django 3.2 on 2023-12-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('route_type', models.CharField(choices=[('Local', 'Local'), ('Inter-town', 'Inter-town')], max_length=10)),
                ('pricing_date_start', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('departure', models.DateTimeField(auto_now_add=True)),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduled_trips.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='scheduled_trips.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='scheduled_trips.station'),
        ),
    ]
