# Generated by Django 3.2 on 2023-12-03 09:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='pricing_date_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
